In [1]:
print("hi")


hi


In [ ]:
"""
Data loading

Train/test split

Scaling

Model training

Confusion matrix

Precision, Recall, Accuracy

ROC & AUC
"""

In [2]:
import pandas as pd
import numpy as np
import sklearn

print("pandas version:", pd.__version__)
print("numpy version:", np.__version__)
print("sklearn version:", sklearn.__version__)


pandas version: 2.1.4
numpy version: 1.26.4
sklearn version: 1.2.2


In [3]:
from sklearn.datasets import load_breast_cancer

data = load_breast_cancer()


In [7]:
print(data.DESCR)

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        worst/largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 0 is Mean Radi

In [8]:
type(data)


sklearn.utils._bunch.Bunch

In [9]:
data.keys()


dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [ ]:
STEP 3 — Convert Data to Pandas DataFrame & Explore It

In [10]:
import pandas as pd

df = pd.DataFrame(data.data, columns=data.feature_names)
df["target"] = data.target


In [11]:
df.head()


mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                 0.07871  ...          17.33           184.60      2019.0   
1                 0.05667  ...          23.41           158.80      1956.0   
2                 0.05999  ...          25.53           152.50      1709.0   
3                 0.09744  ...          26.50            98.87       567.7   
4                 0.05883  ...          16.67           152.20      1575.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   worst symmetry  worst fractal dimension  target  
0          0.4601                  0.11890       0  
1          0.2750                  0.08902       0  
2          0.3613                  0.08758       0  
3          0.6638                  0.17300       0  
4          0.2364                  0.07678       0  

[5 rows x 31 columns]

In [12]:
df.shape


(569, 31)

In [13]:
#STEP 3.4 — Understand the Target Column

In [14]:
df["target"].value_counts()


target
1    357
0    212
Name: count, dtype: int64

In [16]:
#STEP 3.5 — Basic Data Info
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   mean radius              569 non-null    float64
 1   mean texture             569 non-null    float64
 2   mean perimeter           569 non-null    float64
 3   mean area                569 non-null    float64
 4   mean smoothness          569 non-null    float64
 5   mean compactness         569 non-null    float64
 6   mean concavity           569 non-null    float64
 7   mean concave points      569 non-null    float64
 8   mean symmetry            569 non-null    float64
 9   mean fractal dimension   569 non-null    float64
 10  radius error             569 non-null    float64
 11  texture error            569 non-null    float64
 12  perimeter error          569 non-null    float64
 13  area error               569 non-null    float64
 14  smoothness error         5

In [17]:
#STEP 4 — Separate Features (X) and Target (y)
X = df.drop("target", axis=1)


In [18]:
y = df["target"]


In [19]:
X.shape


(569, 30)

In [20]:
y.shape


(569,)

In [22]:
#STEP 5 — Train / Test Split
"""
Goal of STEP 5

Give some data to the model to learn

Keep some data hidden to test it later

This helps us answer:

“Will my model work on NEW data?”

First: Concept (Very Important)

Right now you have:

X → all feature columns

y → target column

But if we train on all data:

The model can memorise

Accuracy becomes fake

Real-world performance fails

So we split the data.
"""

'\nGoal of STEP 5\n\nGive some data to the model to learn\n\nKeep some data hidden to test it later\n\nThis helps us answer:\n\n“Will my model work on NEW data?”\n\nFirst: Concept (Very Important)\n\nRight now you have:\n\nX → all feature columns\n\ny → target column\n\nBut if we train on all data:\n\nThe model can memorise\n\nAccuracy becomes fake\n\nReal-world performance fails\n\nSo we split the data.\n'

In [23]:
#STEP 5.1 — Do the Split

In [24]:
"""
| Name        | Purpose                      |
| ----------- | ---------------------------- |
| **X_train** | Features used for learning   |
| **X_test**  | Features kept hidden         |
| **y_train** | Correct answers for training |
| **y_test**  | Correct answers for testing  |

"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)
"""
test_size=0.2

20% data → test

80% data → train

random_state=42

Ensures same split every time

Helps debugging & reproducibility

📌 Without this, split changes every run.
"""


'\ntest_size=0.2\n\n20% data → test\n\n80% data → train\n'

In [25]:
#STEP 5.2 — Check Shapes

In [26]:
X_train.shape, X_test.shape


((455, 30), (114, 30))

In [27]:
y_train.shape, y_test.shape


((455,), (114,))

In [28]:
#Model will ONLY see X_train & y_train

#X_test & y_test are completely unseen

In [29]:
"""
X, y
 ↓
Train/Test Split
 ↓
Model learns from TRAIN
 ↓
Model evaluated on TEST

-------------------
🚫 Very Important Rule

❌ Never train on test data
❌ Never tune model using test data

That would cause data leakage.

"""

'\nX, y\n ↓\nTrain/Test Split\n ↓\nModel learns from TRAIN\n ↓\nModel evaluated on TEST\n\n'

In [ ]:
#STEP 6 — Train Your First ML Model
"""
🎯 Goal of STEP 6

Create a model

Train it using training data

Understand what “training” actually means

No evaluation yet — only training.
"""

In [ ]:
"""First: What Is Logistic Regression? (Very short)

Used for classification

Outputs probability (between 0 and 1)

Then converts probability → class (0 or 1)"""

In [30]:
#STEP 6.1 — Import the Model

In [31]:
from sklearn.linear_model import LogisticRegression

#STEP 6.2 — Create the Model Object

model = LogisticRegression(max_iter=500)

"""Creates an empty model

No learning yet

max_iter=500 helps convergence

📌 Think:

Model is created, but brain is empty."""

'Creates an empty model\n\nNo learning yet\n\nmax_iter=500 helps convergence\n\n📌 Think:\n\nModel is created, but brain is empty.'

In [32]:
#STEP 6.3 — Train (Fit) the Model

In [33]:
model.fit(X_train, y_train)
"""🧠 THIS is the training step

Model looks at X_train

Compares predictions with y_train

Adjusts internal weights

Repeats until learning stabilizes

📌 After this line → model has learned."""

C:\Users\User\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


'🧠 THIS is the training step\n\nModel looks at X_train\n\nCompares predictions with y_train\n\nAdjusts internal weights\n\nRepeats until learning stabilizes\n\n📌 After this line → model has learned.'

In [35]:
#Above error means Logistic Regression could not fully finish learning within the given number of iterations. So lets find solution
"""Important:

❌ Model did not fail

❌ Training did not stop

⚠️ It just says: “I need a bit more help to learn properly”
Logistic Regression failed to converge because features were on different scales, 
so we applied feature scaling using StandardScaler fitted on training data, which stabilised optimisation.
"""

'mportant:\n\n❌ Model did not fail\n\n❌ Training did not stop\n\n⚠️ It just says: “I need a bit more help to learn properly”'

In [36]:
#STEP 6.5 — Scale the Data

In [37]:
#STEP 6.5.1 — Import Scaler
from sklearn.preprocessing import StandardScaler

#STEP 6.5.2 — Create Scaler
scaler = StandardScaler()

#STEP 6.5.3 — Fit Scaler on TRAINING data ONLY
X_train_scaled = scaler.fit_transform(X_train)

"""🧠 Why only training data?

To avoid data leakage."""

#STEP 6.5.4 — Transform TEST data
X_test_scaled = scaler.transform(X_test)

#📌 We do NOT fit again on test data.
#STEP 6.6 — Train Logistic Regression Again
model = LogisticRegression(max_iter=1000)
model.fit(X_train_scaled, y_train)


LogisticRegression(max_iter=1000)

In [ ]:
"""STEP 7 — Make Predictions on Test Data
🎯 Goal of STEP 7

Use the trained model

Predict labels for unseen data

Prepare for evaluation

No metrics yet — just predictions.

Important Reminder Before We Start

Model was trained on X_train_scaled

So predictions must be made on X_test_scaled

Never mix scaled & unscaled data
"""

In [38]:
#STEP 7.1 — Make Predictions
y_pred = model.predict(X_test_scaled)

"""What Just Happened?

Model saw X_test_scaled for the first time

For each row, it predicted:

0 → malignant

1 → benign

Output stored in y_pred

📌 y_pred is the model’s guesses.
"""

#STEP 7.2 — Quick Sanity Check
y_pred[:10]


array([1, 0, 0, 1, 1, 0, 0, 0, 1, 1])

In [39]:
#STEP 7.3 — Compare Shapes
y_pred.shape, y_test.shape


((114,), (114,))

In [40]:
"""🚀 STEP 8 — Evaluate the Model

You already have:

y_test → actual answers

y_pred → model predictions

Now we compare them.
"""


'🚀 STEP 8 — Evaluate the Model\n\nYou already have:\n\ny_test → actual answers\n\ny_pred → model predictions\n\nNow we compare them.\n'

In [41]:
#STEP 8.1 — Accuracy (Overall Performance)
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)
accuracy

"""What Accuracy Means (Simple)

Out of 100 test samples, how many did the model predict correctly?

📌 This is overall correctness, nothing more."""

0.9736842105263158

In [42]:
#STEP 8.2 — Confusion Matrix (MOST IMPORTANT)
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
cm


array([[41,  2],
       [ 1, 70]], dtype=int64)

In [43]:
#STEP 8.3 - precision, recall calculation
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))


              precision    recall  f1-score   support

           0       0.98      0.95      0.96        43
           1       0.97      0.99      0.98        71

    accuracy                           0.97       114
   macro avg       0.97      0.97      0.97       114
weighted avg       0.97      0.97      0.97       114



In [44]:
"""🚀 STEP 9 — ROC Curve & AUC (Slow & Intuitive)
🧠 Why We Need ROC (Motivation)

So far:

Confusion matrix → fixed threshold (usually 0.5)

Precision / Recall → depend on that threshold

But ML models actually output probabilities, not just 0/1.

👉 ROC answers:

“How does my model behave at ALL possible thresholds?”"""

'🚀 STEP 9 — ROC Curve & AUC (Slow & Intuitive)\n🧠 Why We Need ROC (Motivation)\n\nSo far:\n\nConfusion matrix → fixed threshold (usually 0.5)\n\nPrecision / Recall → depend on that threshold\n\nBut ML models actually output probabilities, not just 0/1.\n\n👉 ROC answers:\n\n“How does my model behave at ALL possible thresholds?”'

In [48]:
"""Step 9.1 — What the Model Actually Outputs

Before predicting classes, the model computes probabilities:"""
y_prob = model.predict_proba(X_test_scaled)
y_prob[:5]


array([[1.14327437e-01, 8.85672563e-01],
       [9.99990961e-01, 9.03924655e-06],
       [9.96901657e-01, 3.09834256e-03],
       [5.10962742e-04, 9.99489037e-01],
       [6.08832659e-05, 9.99939117e-01]])

In [51]:
y_prob_pos = y_prob[:, 1]
y_prob_pos[:5]


array([8.85672563e-01, 9.03924655e-06, 3.09834256e-03, 9.99489037e-01,
       9.99939117e-01])

In [52]:
"""STEP 9.2

Now we compute TPR and F
PR at all thresholds."""

from sklearn.metrics import roc_curve

fpr, tpr, thresholds = roc_curve(y_test, y_prob_pos)


In [53]:
fpr[:5], tpr[:5], thresholds[:5]


(array([0.        , 0.        , 0.        , 0.02325581, 0.02325581]),
 array([0.        , 0.01408451, 0.90140845, 0.90140845, 0.98591549]),
 array([1.99999917, 0.99999917, 0.92734349, 0.91560519, 0.61929378]))

In [54]:
#STEP 9.3 — Compute AUC (FINAL STEP)
from sklearn.metrics import roc_auc_score

auc = roc_auc_score(y_test, y_prob_pos)
auc


0.99737962659679